import { CoverLetterTemplate } from '../types';

// This library is architected to scale to 100+ templates.
// Icons are mapped: 1:Code, 2:Creative, 3:CheckedDoc, 4:Healthcare, 5:Marketing, 6:Corporate, 7:Education
export const templates: CoverLetterTemplate[] = [
  {
    id: 'swe-mid',
    title: 'Mid-Level Software Engineer',
    category: 'Software Development',
    iconId: 1,
    jobDescription: 'Seeking a proficient Software Engineer with 3-5 years of experience in building scalable web applications. Must be skilled in Python, Django, and AWS. Responsibilities include designing and implementing new features, maintaining existing code, and collaborating with cross-functional teams.',
    companyName: 'Innovate Solutions Inc.',
    resumeHighlights: 'Developed and launched three major features for a SaaS product, resulting in a 15% increase in user engagement.\n- Optimized database queries, reducing average response time by 40%.\n- Mentored two junior engineers, improving team productivity.',
    tone: 'Professional',
  },
  {
    id: 'marketing-manager',
    title: 'Digital Marketing Manager',
    category: 'Marketing & Sales',
    iconId: 5,
    jobDescription: 'We are looking for a data-driven Digital Marketing Manager to lead our online marketing efforts. You will be responsible for SEO/SEM, social media, and email marketing campaigns. The ideal candidate has a proven track record of increasing lead generation and brand awareness.',
    companyName: 'Growthify Agency',
    resumeHighlights: 'Led a team of 4 marketers, increasing marketing qualified leads (MQLs) by 75% year-over-year.\n- Managed a $500k annual advertising budget, improving ROI by 30% through A/B testing and campaign optimization.\n- Expert in Google Analytics, Marketo, and Salesforce.',
    tone: 'Confident',
  },
  {
    id: 'ux-designer',
    title: 'UX/UI Designer',
    category: 'Creative & Design',
    iconId: 2,
    jobDescription: 'Join our creative team as a UX/UI Designer to craft intuitive and beautiful user experiences for our mobile and web products. You will conduct user research, create wireframes and prototypes, and work closely with engineers to implement your designs. Portfolio required.',
    companyName: 'Pixel Perfect Studios',
    resumeHighlights: 'Redesigned the user onboarding flow for a mobile app, leading to a 25% reduction in drop-off rates.\n- Proficient in Figma, Sketch, and Adobe Creative Suite.\n- Conducted over 50 user interviews to inform design decisions and product strategy.',
    tone: 'Enthusiastic',
  },
  {
    id: 'new-grad-swe',
    title: 'New Graduate Software Engineer',
    category: 'Student & New Grad',
    iconId: 7,
    jobDescription: 'We are seeking a motivated and talented New Graduate Software Engineer to join our core development team. This is an opportunity to work on challenging problems, learn from experienced mentors, and make a real impact on our product. Basic knowledge of data structures and algorithms is required.',
    companyName: 'NextGen Tech',
    resumeHighlights: 'Computer Science degree with a 3.8 GPA.\n- Developed a full-stack web application for a senior capstone project using React and Node.js.\n- Internship experience at TechCorp, where I contributed to the main codebase and fixed over 20 bugs.',
    tone: 'Enthusiastic',
  },
  {
    id: 'career-change-pm',
    title: 'Career Change to Product Manager',
    category: 'Career Change',
    iconId: 2,
    jobDescription: 'We are open to candidates from non-traditional backgrounds who are looking to transition into a Product Manager role. You must be a strategic thinker, an excellent communicator, and have a passion for solving user problems. We value skills from fields like consulting, analytics, and marketing.',
    companyName: 'Pivotal Products',
    resumeHighlights: '5 years of experience as a business analyst, skilled in stakeholder management and data analysis.\n- Led a cross-functional project that streamlined internal processes, saving the company $100k annually.\n- Completed a Product Management certification from a reputable institution.',
    tone: 'Professional',
  },
  {
    id: 'executive-cfo',
    title: 'Chief Financial Officer (CFO)',
    category: 'Professional & Corporate',
    iconId: 6,
    jobDescription: 'A seasoned Chief Financial Officer is needed to lead our financial strategy and operations. The CFO will be a key member of the executive team, responsible for financial planning, risk management, and investor relations. 15+ years of financial leadership experience required.',
    companyName: 'Global Conglomerate Corp.',
    resumeHighlights: 'As CFO of a Fortune 500 company, successfully managed a $2B budget and led the company through a successful IPO.\n- Secured $150M in Series C funding.\n- Expertise in M&A, strategic planning, and corporate governance.',
    tone: 'Formal',
  },
  {
    id: 'sales-dev-rep',
    title: 'Sales Development Representative',
    category: 'Marketing & Sales',
    iconId: 5,
    jobDescription: 'We are hiring an energetic Sales Development Representative (SDR) to generate and qualify leads for our sales team. You will be responsible for cold calling, emailing, and social outreach to book meetings with potential clients. Strong communication skills and a resilient attitude are a must.',
    companyName: 'ConnectLeads',
    resumeHighlights: 'Consistently exceeded monthly quota by 120% for 6 consecutive months.\n- Praised for my ability to build rapport and handle objections effectively.\n- Proficient with Salesforce and Outreach.io.',
    tone: 'Confident',
  },
  {
    id: 'graphic-designer-entry',
    title: 'Entry-Level Graphic Designer',
    category: 'Student & New Grad',
    iconId: 7,
    jobDescription: 'Seeking a creative and passionate Entry-Level Graphic Designer. You will assist the marketing team in creating visual assets for social media, websites, and print materials. A strong portfolio and proficiency in Adobe Illustrator and Photoshop are required.',
    companyName: 'Artistic Visions',
    resumeHighlights: 'Graduated with a BFA in Graphic Design.\n- Freelance experience designing logos and branding packages for 3 small businesses.\n- My portfolio showcases a strong understanding of typography, color theory, and layout design.',
    tone: 'Enthusiastic',
  },
  {
    id: 'registered-nurse',
    title: 'Registered Nurse (RN)',
    category: 'Healthcare',
    iconId: 4,
    jobDescription: 'Our hospital is seeking a compassionate and skilled Registered Nurse for our Medical-Surgical unit. The RN will be responsible for patient care, administering medications, and collaborating with the healthcare team. Must have a valid RN license and BLS certification.',
    companyName: 'City Central Hospital',
    resumeHighlights: '3 years of experience in a fast-paced hospital environment.\n- Recognized with the "Daisy Award" for extraordinary patient care and compassion.\n- Proficient in using electronic health record (EHR) systems like Epic.',
    tone: 'Professional',
  },
  {
    id: 'teacher-to-instructional-designer',
    title: 'Teacher to Instructional Designer',
    category: 'Career Change',
    iconId: 7,
    jobDescription: 'We are looking for an experienced educator to transition into an Instructional Designer role. You will use your knowledge of learning principles to design engaging and effective training materials for our corporate clients. Experience with Articulate 360 or similar tools is a plus.',
    companyName: 'Learning Innovations',
    resumeHighlights: '10 years of experience as a high school teacher, designing curriculum and assessing learning outcomes.\n- Expert in creating engaging lesson plans and adapting content for diverse learning styles.\n- Strong project management and communication skills.',
    tone: 'Friendly',
  },
  {
    id: 'senior-accountant',
    title: 'Senior Accountant',
    category: 'Professional & Corporate',
    iconId: 6,
    jobDescription: 'Seeking a detail-oriented Senior Accountant to join our finance team. Responsibilities include managing the general ledger, preparing financial statements, and assisting with audits. CPA certification and 5+ years of accounting experience required.',
    companyName: 'Precision Financials',
    resumeHighlights: 'Managed month-end closing process for a $50M company, ensuring accuracy and timeliness.\n- Identified a process inefficiency that saved the company 20 hours of labor per month.\n- Expert in QuickBooks, SAP, and Microsoft Excel.',
    tone: 'Formal',
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    category: 'Software Development',
    iconId: 1,
    jobDescription: 'We are hiring a Data Scientist to analyze large datasets and generate insights that will drive our business strategy. You will build machine learning models, perform statistical analysis, and communicate your findings to stakeholders. PhD or MS in a quantitative field preferred.',
    companyName: 'Data Insights Co.',
    resumeHighlights: 'Developed a predictive model that improved customer retention by 10%.\n- Published 3 papers in peer-reviewed journals on machine learning topics.\n- Proficient in Python (pandas, scikit-learn), R, SQL, and Tableau.',
    tone: 'Professional',
  },
  {
    id: 'it-project-manager',
    title: 'IT Project Manager',
    category: 'Professional & Corporate',
    iconId: 6,
    jobDescription: 'Seeking an experienced IT Project Manager to oversee the planning and execution of our technology projects. Must have a PMP certification and a proven track record of delivering projects on time and within budget. Experience with Agile methodologies is essential.',
    companyName: 'Tech Systems United',
    resumeHighlights: 'Managed a portfolio of 5 concurrent IT projects with a total budget of $2.5M.\n- Implemented a new Agile workflow that increased team velocity by 30%.\n- Certified PMP and Scrum Master with 8 years of project management experience.',
    tone: 'Professional',
  },
  {
    id: 'financial-analyst',
    title: 'Financial Analyst',
    category: 'Professional & Corporate',
    iconId: 6,
    jobDescription: 'A detail-oriented Financial Analyst is needed to support our finance department. Responsibilities include financial modeling, variance analysis, and preparing reports for senior management. Strong Excel skills and a degree in Finance or Accounting are required.',
    companyName: 'Capital Investments Group',
    resumeHighlights: 'Built complex financial models to support a $50M acquisition deal.\n- Created a new monthly reporting package that improved visibility into departmental spending.\n- Advanced proficiency in Excel (PivotTables, VLOOKUP) and financial modeling.',
    tone: 'Formal',
  },
  {
    id: 'hr-generalist',
    title: 'Human Resources Generalist',
    category: 'Professional & Corporate',
    iconId: 6,
    jobDescription: 'We are looking for a versatile HR Generalist to manage our day-to-day HR operations. This role covers employee relations, recruitment, onboarding, and benefits administration. A PHR or SHRM-CP certification is highly desirable.',
    companyName: 'PeopleFirst Corp.',
    resumeHighlights: 'Managed the full-cycle recruitment process for over 50 roles, reducing average time-to-fill by 15 days.\n- Resolved 95% of employee relations issues without escalation.\n- Implemented a new HRIS system, improving data accuracy and efficiency.',
    tone: 'Friendly',
  },
  {
    id: 'customer-service-manager',
    title: 'Customer Service Manager',
    category: 'Professional & Corporate',
    iconId: 3,
    jobDescription: 'A passionate Customer Service Manager is needed to lead our support team. You will be responsible for improving customer satisfaction, training and mentoring staff, and developing service procedures. 5+ years in a customer-facing leadership role required.',
    companyName: 'ClientCare Solutions',
    resumeHighlights: 'Led a team of 15 support agents to achieve a 98% customer satisfaction (CSAT) score for three consecutive quarters.\n- Developed a comprehensive training program that reduced agent onboarding time by 50%.\n- Expert in Zendesk and Intercom.',
    tone: 'Confident',
  },
  {
    id: 'content-writer',
    title: 'Content Writer',
    category: 'Creative & Design',
    iconId: 2,
    jobDescription: 'We are hiring a creative Content Writer to produce high-quality blog posts, website copy, and marketing materials. The ideal candidate has excellent writing and editing skills, an understanding of SEO best practices, and the ability to adapt their writing style to different audiences.',
    companyName: 'StoryWeavers Inc.',
    resumeHighlights: 'Wrote over 100 blog posts, contributing to a 200% increase in organic website traffic.\n- My article on "Digital Marketing Trends" was featured on a major industry publication.\n- Skilled in SEO keyword research and content optimization using tools like Ahrefs.',
    tone: 'Enthusiastic',
  },
  {
    id: 'paralegal',
    title: 'Paralegal',
    category: 'Professional & Corporate',
    iconId: 6,
    jobDescription: 'A reputable law firm seeks a diligent and organized Paralegal to support our litigation team. Responsibilities include legal research, drafting documents, and managing case files. A paralegal certificate and experience with e-discovery software are required.',
    companyName: 'Thompson & Associates Law',
    resumeHighlights: 'Assisted in trial preparation for three major cases, all of which resulted in favorable outcomes.\n- Managed a caseload of over 30 active files, ensuring all deadlines were met.\n- Proficient in legal research databases like Westlaw and LexisNexis.',
    tone: 'Formal',
  },
  {
    id: 'civil-engineer',
    title: 'Civil Engineer',
    category: 'Professional & Corporate',
    iconId: 3,
    jobDescription: 'Seeking a licensed Civil Engineer to join our infrastructure projects team. The role involves site design, calculations, and project management for public works projects. Proficiency in AutoCAD and Civil 3D is a must.',
    companyName: 'Urban Development Partners',
    resumeHighlights: 'Managed the design and construction of a $10M municipal road improvement project.\n- PE license in Civil Engineering.\n- Expertise in stormwater management design and transportation engineering.',
    tone: 'Professional',
  },
  {
    id: 'research-scientist',
    title: 'Research Scientist',
    category: 'Healthcare',
    iconId: 4,
    jobDescription: 'Our biotech firm is hiring a Research Scientist to contribute to our drug discovery program. Candidates should have a PhD in Biology or a related field and hands-on experience with molecular biology techniques.',
    companyName: 'BioGen Innovations',
    resumeHighlights: 'Co-authored 5 publications in high-impact scientific journals.\n- Developed a novel assay that accelerated our research timeline by 3 months.\n- Expertise in CRISPR gene editing and cell-based assays.',
    tone: 'Formal',
  },
  {
    id: 'non-profit-coordinator',
    title: 'Non-Profit Program Coordinator',
    category: 'Career Change',
    iconId: 3,
    jobDescription: 'A passionate Program Coordinator is needed to manage our community outreach initiatives. Responsibilities include event planning, volunteer management, and grant reporting. Experience in the non-profit sector is highly valued.',
    companyName: 'Hope For All Foundation',
    resumeHighlights: 'Organized an annual fundraising gala that raised over $250,000.\n- Recruited and managed a team of over 100 volunteers for various events.\n- Contributed to two successful grant applications, securing $75,000 in funding.',
    tone: 'Friendly',
  },
  {
    id: 'elementary-teacher',
    title: 'Elementary School Teacher',
    category: 'Student & New Grad',
    iconId: 7,
    jobDescription: 'A vibrant elementary school is seeking a dedicated 3rd Grade Teacher for the upcoming school year. The ideal candidate will have a passion for education, strong classroom management skills, and a valid teaching credential.',
    companyName: 'Oakwood Elementary School',
    resumeHighlights: 'Student teaching experience in a 3rd-grade classroom, where I designed and implemented a 4-week science unit.\n- Praised for my ability to create an inclusive and engaging learning environment.\n- Familiar with Common Core standards and differentiated instruction techniques.',
    tone: 'Enthusiastic',
  },
  {
    id: 'physician-assistant',
    title: 'Physician Assistant',
    category: 'Healthcare',
    iconId: 4,
    jobDescription: 'A busy family medicine clinic is hiring a certified Physician Assistant. You will work collaboratively with physicians to provide comprehensive patient care, including diagnosing illnesses, developing treatment plans, and educating patients.',
    companyName: 'Community Health Clinic',
    resumeHighlights: 'NCCPA certified Physician Assistant with 2 years of experience in a primary care setting.\n- Managed a panel of over 500 patients, consistently receiving positive patient feedback.\n- Skilled in performing minor procedures and interpreting lab results.',
    tone: 'Professional',
  }
];